import heroLivingImg from "@/assets/images/hero_minimalist_living_1790374708567.jpg";
import audioTurntableImg from "@/assets/images/product_audio_turntable_1790374718999.jpg";
import ceramicVesselImg from "@/assets/images/product_ceramic_vessel_1790374728437.jpg";
import leatherToteImg from "@/assets/images/product_leather_tote_1790374738935.jpg";
import loungeChairImg from "@/assets/images/product_lounge_chair_1790374749725.jpg";
import { Category, Product, Order, ContactMessage } from "@/types";

export const HERO_IMAGE = heroLivingImg;

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Studio Audio",
    slug: "studio-audio",
    description: "Precision acoustic hardware engineered with monolithic geometry and raw architectural materials.",
    image: audioTurntableImg,
    itemCount: 4,
  },
  {
    id: "cat-2",
    name: "Ceramics & Objects",
    slug: "ceramics-objects",
    description: "Handcrafted stoneware and tactile vessels fired with unglazed natural minerals.",
    image: ceramicVesselImg,
    itemCount: 5,
  },
  {
    id: "cat-3",
    name: "Leather Goods",
    slug: "leather-goods",
    description: "Vegetable-tanned full-grain leather pieces crafted with architectural fold lines.",
    image: leatherToteImg,
    itemCount: 4,
  },
  {
    id: "cat-4",
    name: "Minimalist Furniture",
    slug: "minimalist-furniture",
    description: "Solid hardwood seating and sculptural tables built for enduring spatial tranquility.",
    image: loungeChairImg,
    itemCount: 4,
  },
  {
    id: "cat-5",
    name: "Tactile Homeware",
    slug: "tactile-homeware",
    description: "Everyday ritual objects formed from brushed aluminum, smoked glass, and raw linen.",
    image: heroLivingImg,
    itemCount: 3,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "K-01 Linear Precision Turntable",
    slug: "k-01-linear-precision-turntable",
    categorySlug: "studio-audio",
    categoryName: "Studio Audio",
    price: 840,
    originalPrice: 920,
    description: "A precision belt-driven analog turntable machined from solid anodized aluminum and dampening composite. Designed to eliminate mechanical resonance while presenting an ultra-pure acoustic frequency response.",
    features: [
      "Crafted from premium sustainable materials with exceptional structural integrity",
      "Designed for spatial balance, minimalist clarity, and long-lasting durability",
      "Finished by hand in small artisanal batches with natural protective treatments",
      "Accompanied by an individual certificate of authenticity and numbered release"
    ],
    images: [audioTurntableImg, heroLivingImg, audioTurntableImg],
    sizes: ["Standard", "Audiophile Pro Platter"],
    colors: ["Matte Black", "Brushed Silver", "Monolith Slate"],
    stock: 7,
    isAvailable: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    id: "prod-2",
    name: "Forma Textured Stoneware Vessel",
    slug: "forma-textured-stoneware-vessel",
    categorySlug: "ceramics-objects",
    categoryName: "Ceramics & Objects",
    price: 185,
    description: "Hand-thrown high-fire stoneware vessel featuring an organic textured exterior finish and water-sealed interior. Each piece demonstrates subtle variations in surface contour and mineral tone.",
    features: [
      "Individually hand-thrown in small batches by ceramic artisans",
      "Tactile unglazed coarse grog clay body with warm undertones",
      "Water-safe vitreous interior lining for floral arrangements",
      "Protective soft wool felt base pad to prevent surface marking"
    ],
    images: [ceramicVesselImg, heroLivingImg, ceramicVesselImg],
    sizes: ["Small (22cm)", "Medium (30cm)", "Large (38cm)"],
    colors: ["Warm Travertine", "Charcoal Slip", "Chalk White"],
    stock: 14,
    isAvailable: true,
    isBestSeller: true,
    isNew: true,
    specs: {
      "Material": "Natural coarse stoneware clay",
      "Origin": "Kyoto Atelier Studio",
      "Care": "Hand wash with mild neutral detergent",
    },
  },
  {
    id: "prod-3",
    name: "Architectural Raw Leather Tote",
    slug: "architectural-raw-leather-tote",
    categorySlug: "leather-goods",
    categoryName: "Leather Goods",
    price: 420,
    description: "Cut from 3.2mm full-grain Tuscan vegetable-tanned leather. Features origami-inspired gusset folds that maintain clean geometric lines whether empty or carrying daily essentials.",
    features: [
      "Grade-A vegetable-tanned bovine leather with untreated edges",
      "Internal dedicated compartment fits up to 16-inch laptops",
      "Hand-peened solid brass hardware with matte tumbled finish",
      "Seamless reinforced base panel for lifetime durability"
    ],
    images: [leatherToteImg, heroLivingImg, leatherToteImg],
    sizes: ["Compact (13-inch)", "Standard (16-inch)"],
    colors: ["Deep Pitch Black", "Saddle Tan", "Cast Espresso"],
    stock: 9,
    isAvailable: true,
    isBestSeller: true,
    isNew: false,
    specs: {
      "Dimensions": "390 x 340 x 120 mm",
      "Drop Length": "240 mm shoulder drop",
      "Weight": "920 g",
    },
  },
  {
    id: "prod-4",
    name: "Ovo Sculptural Bouclé Lounge Chair",
    slug: "ovo-sculptural-boucle-lounge-chair",
    categorySlug: "minimalist-furniture",
    categoryName: "Minimalist Furniture",
    price: 1350,
    originalPrice: 1500,
    description: "Defined by continuous fluid curves and architectural restraint. Features an internal solid ash frame upholstered in heavy-weight textured wool-cotton bouclé for exceptional lumbar comfort.",
    features: [
      "Kiln-dried solid FSC-certified ash interior skeleton",
      "High-resilience multi-density polyurethane foam core",
      "Heavyweight textured Italian bouclé (45,000 Martindale rubs)",
      "Recessed base creates an elegant floating shadow gap"
    ],
    images: [loungeChairImg, heroLivingImg, loungeChairImg],
    sizes: ["Standard Lounge", "Grand Lounge (+15%)"],
    colors: ["Ivory Bouclé", "Smoked Charcoal", "Oatmeal Melange"],
    stock: 4,
    isAvailable: true,
    isBestSeller: true,
    isNew: true,
    specs: {
      "Dimensions": "820 x 860 x 740 mm",
      "Seat Height": "410 mm",
      "Weight": "24 kg",
      "Assembly": "Delivered fully assembled in wooden crate",
    },
  },
  {
    id: "prod-5",
    name: "Aero Monolith Bluetooth Monitor",
    slug: "aero-monolith-bluetooth-monitor",
    categorySlug: "studio-audio",
    categoryName: "Studio Audio",
    price: 680,
    description: "Compact active acoustic monitor encased in seamless cast aluminum. Custom planar magnetic drivers deliver studio-grade transparency with Bluetooth 5.3 aptX lossless capability.",
    features: [
      "Custom 4.5-inch woven carbon fiber mid-bass driver",
      "Dual Class-D amplifiers delivering 120W total clean power",
      "Integrated 24-bit/192kHz DAC with USB-C and optical inputs",
      "Machined volume knob with tactile 32-step indexing"
    ],
    images: [audioTurntableImg, loungeChairImg],
    sizes: ["Single Unit", "Calibrated Stereo Pair"],
    colors: ["Matte Black", "Anodized Silver"],
    stock: 11,
    isAvailable: true,
    isBestSeller: false,
    isNew: true,
    specs: {
      "Frequency Response": "42 Hz – 28 kHz",
      "Wireless": "Bluetooth 5.3 aptX Lossless, AAC",
      "Weight": "4.8 kg per unit",
    },
  },
  {
    id: "prod-6",
    name: "Cylinder Smoked Glass Decanter Set",
    slug: "cylinder-smoked-glass-decanter-set",
    categorySlug: "tactile-homeware",
    categoryName: "Tactile Homeware",
    price: 160,
    description: "Mouth-blown borosilicate glassware with subtle smoke gray graduation. Includes a 1000ml faceted decanter and two weighted matching tumblers.",
    features: [
      "Hand-blown heat-resistant borosilicate glass composition",
      "Ground glass airtight stopper for spirit preservation",
      "Comfortable weighted base with precision laser-etched badge",
      "Lead-free and food-safe certified construction"
    ],
    images: [ceramicVesselImg, heroLivingImg],
    sizes: ["Standard Decanter + 2 Glasses", "Decanter + 4 Glasses"],
    colors: ["Smoked Mineral", "Clear Optic", "Amber Hue"],
    stock: 18,
    isAvailable: true,
    isBestSeller: false,
    isNew: false,
    specs: {
      "Decanter Capacity": "1000 ml",
      "Tumbler Capacity": "320 ml each",
      "Dishwasher Safe": "Top rack recommended",
    },
  },
  {
    id: "prod-7",
    name: "Templo Solid Ash Coffee Table",
    slug: "templo-solid-ash-coffee-table",
    categorySlug: "minimalist-furniture",
    categoryName: "Minimalist Furniture",
    price: 980,
    description: "Low-profile geometric table with substantial cylindrical legs and a thick beveled edge. Finished with natural matte organic wax that highlights the open grain of ash timber.",
    features: [
      "Solid European white ash from sustainably managed forests",
      "Hand-rubbed natural low-VOC plant-based oil finish",
      "Mortise and tenon joinery built without visible fasteners",
      "Soft chamfered perimeter edge profile"
    ],
    images: [heroLivingImg, loungeChairImg],
    sizes: ["100cm Round", "130cm Oblong"],
    colors: ["Bleached Ash", "Natural Ash", "Ebonized Black"],
    stock: 5,
    isAvailable: true,
    isBestSeller: false,
    isNew: false,
    specs: {
      "Height": "320 mm",
      "Diameter": "1000 mm",
      "Weight": "32 kg",
    },
  },
  {
    id: "prod-8",
    name: "Folded Card Wallet in Cast Nero",
    slug: "folded-card-wallet-in-cast-nero",
    categorySlug: "leather-goods",
    categoryName: "Leather Goods",
    price: 110,
    description: "Created from a single piece of full-grain leather folded without stitches. Holds up to 8 cards and folded banknotes with minimal pocket footprint.",
    features: [
      "Single-pattern seamless origami fold design",
      "Hand-buffed edges burnished with natural beeswax",
      "Develops a deep personalized patina with daily use",
      "Debossed minimal studio typographic marking"
    ],
    images: [leatherToteImg, ceramicVesselImg],
    sizes: ["Slim (6-8 cards)"],
    colors: ["Cast Nero", "Natural Tan", "Olive Drab"],
    stock: 22,
    isAvailable: true,
    isBestSeller: true,
    isNew: false,
    specs: {
      "Dimensions": "100 x 68 x 8 mm",
      "Weight": "38 g",
    },
  }
];

export const ABOUT_CONTENT = {
  title: "A Study in Monolithic Geometry & Restraint",
  paragraphs: [
    "KØRD is a dedicated design studio and commerce platform focused on reduction. We operate on the premise that everyday objects should elevate human focus rather than compete for attention.",
    "Every artifact in our collection is created or curated through rigorous material scrutiny: tactile untreated leather, precision-milled aluminum, unglazed stoneware, and solid timber. There are no ornamental distractions or transient trends.",
    "Manufactured in small audited atelier batches across Kyoto, Copenhagen, and Milan, our products are engineered for decades of continuous quiet presence."
  ],
  stats: [
    { label: "Material Longevity", value: "25+ Yrs" },
    { label: "Atelier Partnerships", value: "12 Studios" },
    { label: "Zero Synthetic Finishes", value: "100% Pure" },
    { label: "Plastic-Free Packaging", value: "Verified" },
  ]
};

export const CONTACT_INFO = {
  conciergeEmail: "studio@kord-objects.com",
  orderAssistance: "+1 (800) 482-9021",
  studioAddress: "74 Bleeker Street, Studio 4B, New York, NY 10012",
  hours: "Monday – Friday: 09:00 – 18:00 EST",
};

export const INITIAL_ORDERS: import("@/types").Order[] = [
  {
    id: "KRD-841920",
    customer: {
      firstName: "Henrik",
      lastName: "Lindqvist",
      phoneNumber: "+1 (555) 234-8901",
      address: "88 Franklin St, Apt 4B, Tribeca, New York, NY 10013",
      notes: "Please leave package with doorman. Fragile stoneware included.",
    },
    items: [
      {
        id: "prod-1-Standard-Matte Black",
        productId: "prod-1",
        product: PRODUCTS[0],
        quantity: 1,
        selectedSize: "Standard",
        selectedColor: "Matte Black",
        price: 840,
      },
      {
        id: "prod-2-Medium (30cm)-Warm Travertine",
        productId: "prod-2",
        product: PRODUCTS[1],
        quantity: 1,
        selectedSize: "Medium (30cm)",
        selectedColor: "Warm Travertine",
        price: 185,
      },
    ],
    subtotal: 1025,
    shippingFee: 0,
    total: 1025,
    createdAt: "2026-09-24T14:32:00Z",
    status: "confirmed",
  },
  {
    id: "KRD-719302",
    customer: {
      firstName: "Elena",
      lastName: "Rostova",
      phoneNumber: "+1 (555) 987-1234",
      address: "410 Marlborough St, Boston, MA 02115",
      notes: "Gate code is #4820. Deliver to back porch.",
    },
    items: [
      {
        id: "prod-4-Standard Lounge-Ivory Bouclé",
        productId: "prod-4",
        product: PRODUCTS[3],
        quantity: 1,
        selectedSize: "Standard Lounge",
        selectedColor: "Ivory Bouclé",
        price: 1350,
      },
    ],
    subtotal: 1350,
    shippingFee: 0,
    total: 1350,
    createdAt: "2026-09-23T11:15:00Z",
    status: "processing",
  },
  {
    id: "KRD-604812",
    customer: {
      firstName: "Julian",
      lastName: "Thorne",
      phoneNumber: "+1 (555) 432-8765",
      address: "1204 Pine Street, San Francisco, CA 94109",
      notes: "Direct recipient signature required.",
    },
    items: [
      {
        id: "prod-3-Standard (16-inch)-Deep Pitch Black",
        productId: "prod-3",
        product: PRODUCTS[2],
        quantity: 1,
        selectedSize: "Standard (16-inch)",
        selectedColor: "Deep Pitch Black",
        price: 420,
      },
    ],
    subtotal: 420,
    shippingFee: 25,
    total: 445,
    createdAt: "2026-09-22T09:40:00Z",
    status: "shipped",
  },
  {
    id: "KRD-529104",
    customer: {
      firstName: "Astrid",
      lastName: "Bergman",
      phoneNumber: "+1 (555) 678-3456",
      address: "72 Bellevue Ave, Newport, RI 02840",
      notes: "Gift packaging requested with studio seal.",
    },
    items: [
      {
        id: "prod-6-Standard Decanter + 2 Glasses-Smoked Mineral",
        productId: "prod-6",
        product: PRODUCTS[5],
        quantity: 1,
        selectedSize: "Standard Decanter + 2 Glasses",
        selectedColor: "Smoked Mineral",
        price: 160,
      },
    ],
    subtotal: 160,
    shippingFee: 25,
    total: 185,
    createdAt: "2026-09-21T16:50:00Z",
    status: "delivered",
  },
  {
    id: "KRD-418290",
    customer: {
      firstName: "Marcus",
      lastName: "Vance",
      phoneNumber: "+1 (555) 890-5678",
      address: "1530 West Division St, Chicago, IL 60622",
      notes: "Calling prior to delivery appreciated.",
    },
    items: [
      {
        id: "prod-5-Single Unit-Matte Black",
        productId: "prod-5",
        product: PRODUCTS[4],
        quantity: 1,
        selectedSize: "Single Unit",
        selectedColor: "Matte Black",
        price: 680,
      },
    ],
    subtotal: 680,
    shippingFee: 0,
    total: 680,
    createdAt: "2026-09-20T18:20:00Z",
    status: "pending",
  },
  {
    id: "KRD-382911",
    customer: {
      firstName: "Sophie",
      lastName: "Laurent",
      phoneNumber: "+1 (555) 123-9988",
      address: "240 Mercer Street, New York, NY 10012",
      notes: "Customer requested cancellation before batch assembly.",
    },
    items: [
      {
        id: "prod-8-Slim (6-8 cards)-Cast Nero",
        productId: "prod-8",
        product: PRODUCTS[7],
        quantity: 1,
        selectedSize: "Slim (6-8 cards)",
        selectedColor: "Cast Nero",
        price: 110,
      },
    ],
    subtotal: 110,
    shippingFee: 25,
    total: 135,
    createdAt: "2026-09-19T13:05:00Z",
    status: "cancelled",
  },
];

export const INITIAL_CONTACT_MESSAGES: ContactMessage[] = [
  {
    id: "msg-101",
    name: "Yacine Belkacem",
    email: "yacine.b@archidesign.dz",
    subject: "Custom dimension inquiry for M-02 Lounge Chair",
    message: "Bonjour, we are specifying furniture for an architectural studio in Hydra, Algiers. Can the solid ash frame of the M-02 Lounge Chair be treated with a bespoke matte walnut stain, and what would be the lead time for 4 units?",
    createdAt: "2026-09-25T14:32:00Z",
    status: "unread",
  },
  {
    id: "msg-102",
    name: "Elena Rostova",
    email: "elena.rostova@designhaus.com",
    subject: "K-01 Linear Precision Turntable cartridge compatibility",
    message: "Does the K-01 turntable tonearm support balanced XLR output or standard gold-plated RCA with dedicated grounding? Also inquiring about international express courier options to Oran.",
    createdAt: "2026-09-24T09:15:00Z",
    status: "unread",
  },
  {
    id: "msg-103",
    name: "Karim Mebarki",
    email: "karim.mebarki@gmail.com",
    subject: "Ceramic vessel stoneware care instructions",
    message: "I received the C-03 vessel yesterday in pristine condition. I would like to confirm if the inner mineral glaze is safe for fresh flower water, or if it is purely meant for dry botanical stems.",
    createdAt: "2026-09-23T18:40:00Z",
    status: "read",
  },
  {
    id: "msg-104",
    name: "Nadia Benali",
    email: "nadia.b@studioalger.com",
    subject: "Corporate order for atelier leather sleeves",
    message: "We would like to place an order of 15 L-01 Architect Folios embossed with our studio logo. Could you provide a formal quote and delivery timeframe?",
    createdAt: "2026-09-21T11:20:00Z",
    status: "replied",
    notes: "Quotation sent via concierge email on Sept 22.",
  },
];

