import heroClothingImg from "@/assets/images/hero_menswear_duo_1790715310965.jpg";
import prodBoxyTee from "@/assets/images/prod_boxyt_shirt_1790714551320.jpg";
import prodTailoredPants from "@/assets/images/prod_tailored_pants_1790714562232.jpg";
import prodLeatherShoes from "@/assets/images/prod_leather_shoes_1790714573794.jpg";
import prodDerbyShoes from "@/assets/images/prod_derby_shoes_1790714587137.jpg";
import prodGraphicTee from "@/assets/images/prod_graphic_tee_1790714599285.jpg";
import { Category, Product, Order, ContactMessage, StoreSettings } from "@/types";

export const HERO_IMAGE = heroClothingImg;

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "T-Shirts",
    slug: "t-shirts",
    description: "Heavyweight organic cotton t-shirts, boxy oversized silhouettes, and architectural basics.",
    image: prodBoxyTee,
    itemCount: 3,
  },
  {
    id: "cat-2",
    name: "Pants",
    slug: "pants",
    description: "Pleated wide-leg trousers, relaxed structured chinos, and minimalist utility pants.",
    image: prodTailoredPants,
    itemCount: 3,
  },
  {
    id: "cat-3",
    name: "Shoes",
    slug: "shoes",
    description: "Minimalist leather sneakers, chunky lug-sole derbies, and modern contemporary footwear.",
    image: prodLeatherShoes,
    itemCount: 2,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Heavyweight Boxy Crewneck Tee",
    slug: "heavyweight-boxy-crewneck-tee",
    categorySlug: "t-shirts",
    categoryName: "T-Shirts",
    price: 3600,
    originalPrice: 4200,
    description: "Heavyweight 280 GSM combed organic cotton t-shirt cut with a relaxed boxy fit, dropped shoulders, and a clean ribbed collar. Preshrunk to maintain its structured silhouette wash after wash.",
    features: [
      "280 GSM heavyweight 100% combed organic cotton",
      "Relaxed architectural boxy silhouette with dropped shoulders",
      "High-density twin-needle stitching at collar and hem",
      "Garment-dyed and preshrunk for an ultra-soft hand feel",
    ],
    images: [prodBoxyTee, prodGraphicTee, heroClothingImg],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Washed Black", "Heather Gray", "Chalk White"],
    stock: 35,
    isAvailable: true,
    isBestSeller: true,
    isNew: false,
    specs: {
      "Fabric": "100% Organic Combed Cotton",
      "Weight": "280 GSM Heavyweight",
      "Cut": "Boxy Oversized Fit",
      "Care": "Machine wash cold inside out, hang dry",
    },
  },
  {
    id: "prod-2",
    name: "Architectural Mockneck Heavy Tee",
    slug: "architectural-mockneck-heavy-tee",
    categorySlug: "t-shirts",
    categoryName: "T-Shirts",
    price: 4500,
    description: "Minimalist mockneck t-shirt constructed from dense 300 GSM cotton jersey. Features a snug architectural neck rib and clean straight hem designed to drape with structured elegance.",
    features: [
      "Dense 300 GSM interlock cotton jersey",
      "Architectural 3.5cm ribbed mockneck collar",
      "Seamless side construction for pure natural draping",
      "Fade-resistant reactive pigment dye",
    ],
    images: [prodBoxyTee, prodGraphicTee],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Charcoal Black", "Concrete Gray", "Cast Bone"],
    stock: 24,
    isAvailable: true,
    isBestSeller: true,
    isNew: true,
    specs: {
      "Fabric": "100% Interlock Cotton",
      "Weight": "300 GSM Heavyweight",
      "Collar": "3.5cm Mockneck Rib",
      "Care": "Machine wash delicate cold, lay flat to dry",
    },
  },
  {
    id: "prod-3",
    name: "Studio Minimal Typographic Tee",
    slug: "studio-minimal-typographic-tee",
    categorySlug: "t-shirts",
    categoryName: "T-Shirts",
    price: 3800,
    description: "Subtle statement t-shirt featuring minimal monochromatic studio typography across the upper back. Cut in our signature relaxed block from vintage-washed organic cotton.",
    features: [
      "260 GSM single jersey organic cotton",
      "High-definition tonal screenprint on upper back",
      "Reinforced shoulder-to-shoulder herringbone taping",
      "Vintage enzyme wash for subtle character and drape",
    ],
    images: [prodGraphicTee, prodBoxyTee],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Chalk White", "Pitch Black", "Ash Gray"],
    stock: 28,
    isAvailable: true,
    isBestSeller: false,
    isNew: true,
    specs: {
      "Fabric": "100% Organic Cotton",
      "Weight": "260 GSM",
      "Fit": "Relaxed Regular Fit",
      "Care": "Machine wash cold, iron inside out",
    },
  },
  {
    id: "prod-4",
    name: "Pleated Wide-Leg Tailored Trousers",
    slug: "pleated-wide-leg-tailored-trousers",
    categorySlug: "pants",
    categoryName: "Pants",
    price: 5400,
    originalPrice: 6200,
    description: "Architectural tailored pants featuring double front reverse pleats, a fluid wide-leg cut, and an internal adjustable tab waistband. Crafted from a high-drape tropical wool-viscose blend for movement and breathability.",
    features: [
      "Crease-resistant fluid wool-viscose blend (320 GSM)",
      "Double reverse front pleats for architectural volume",
      "Concealed hook-and-bar closure with side waistband adjusters",
      "Deep slanted trouser pockets and rear welt pockets",
    ],
    images: [prodTailoredPants, heroClothingImg],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Dark Charcoal", "Midnight Black", "Sandstone Beige"],
    stock: 18,
    isAvailable: true,
    isBestSeller: true,
    isNew: false,
    specs: {
      "Material": "65% Polyester, 32% Viscose, 3% Elastane",
      "Cut": "Wide-Leg Tailored Silhouette",
      "Waistband": "Concealed hook & internal side tabs",
      "Care": "Dry clean or gentle hand wash",
    },
  },
  {
    id: "prod-5",
    name: "Relaxed Structured Chino Pants",
    slug: "relaxed-structured-chino-pants",
    categorySlug: "pants",
    categoryName: "Pants",
    price: 4600,
    description: "Everyday relaxed trousers made from durable 10oz cotton twill with a gentle peach finish. Features a straight relaxed leg, slightly cropped break, and clean interior taped seams.",
    features: [
      "10oz Japanese cotton twill with brushed finish",
      "Relaxed straight silhouette with clean break",
      "Reinforced bar-tacking at all stress points",
      "Natural horn buttons and premium brass zip fly",
    ],
    images: [prodTailoredPants, prodBoxyTee],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Slate Gray", "Onyx Black", "Olive Drab"],
    stock: 22,
    isAvailable: true,
    isBestSeller: false,
    isNew: true,
    specs: {
      "Material": "100% Brushed Cotton Twill",
      "Weight": "10oz / 340 GSM",
      "Cut": "Relaxed Straight Cut",
      "Care": "Machine wash warm, tumble dry low",
    },
  },
  {
    id: "prod-6",
    name: "Minimalist Architectural Utility Pants",
    slug: "minimalist-architectural-utility-pants",
    categorySlug: "pants",
    categoryName: "Pants",
    price: 5800,
    description: "Modern functional pants with flush side cargo pockets and articulated knee darts. Constructed from water-repellent stretch ripstop cotton designed for all-day urban comfort.",
    features: [
      "Durable water-repellent stretch ripstop weave",
      "Flush ergonomic cargo pockets with magnetic closures",
      "Articulated knees for effortless mobility",
      "Elasticized waist back with concealed drawcord",
    ],
    images: [prodTailoredPants, heroClothingImg],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Pitch Black", "Cast Gray", "Forest Olive"],
    stock: 16,
    isAvailable: true,
    isBestSeller: true,
    isNew: true,
    specs: {
      "Material": "97% Cotton, 3% Spandex Ripstop",
      "Pockets": "6 Ergonomic Pockets",
      "Feature": "Water-Repellent DWR Finish",
      "Care": "Machine wash cold with like colors",
    },
  },
  {
    id: "prod-7",
    name: "Minimalist Low-Top Leather Sneakers",
    slug: "minimalist-low-top-leather-sneakers",
    categorySlug: "shoes",
    categoryName: "Shoes",
    price: 7500,
    originalPrice: 8500,
    description: "Pared-back luxury sneakers crafted from full-grain calfskin leather with a cushioned Margom-style cupsole. Designed with clean unpadded lines and wax-dipped cotton laces.",
    features: [
      "Italian full-grain calfskin leather upper and calf lining",
      "Durable stitched rubber cupsole with anti-slip tread",
      "Removable cushioned memory foam arch support insole",
      "Wax-coated flat cotton laces with debossed tongue logo",
    ],
    images: [prodLeatherShoes, heroClothingImg],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Off-White & Gray", "Triple Black", "Chalk Gray"],
    stock: 20,
    isAvailable: true,
    isBestSeller: true,
    isNew: false,
    specs: {
      "Upper": "100% Full-Grain Calfskin Leather",
      "Sole": "Vulcanized Natural Rubber Cupsole",
      "Lining": "Soft Breathable Calf Leather",
      "Origin": "Porto Footwear Workshop",
    },
  },
  {
    id: "prod-8",
    name: "Monolith Lug-Sole Leather Derby Shoes",
    slug: "monolith-lug-sole-leather-derby-shoes",
    categorySlug: "shoes",
    categoryName: "Shoes",
    price: 8800,
    description: "Substantial round-toe derby shoes constructed with smooth polished box leather mounted on a lightweight EVA lug commando sole. Delivers a bold contemporary silhouette with everyday walkability.",
    features: [
      "Smooth semi-gloss box calf leather",
      "Ultra-lightweight chunky lug commando sole (4.5cm platform)",
      "Storm welted construction for lifelong resoleability",
      "Reinforced heel counter and cushioned leather footbed",
    ],
    images: [prodDerbyShoes, heroClothingImg],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Polished Black", "Charcoal Gray", "Espresso Brown"],
    stock: 14,
    isAvailable: true,
    isBestSeller: true,
    isNew: true,
    specs: {
      "Upper": "Polished Box Calf Leather",
      "Sole": "Extralight® EVA Lug Sole (45mm)",
      "Construction": "Storm Welted Stitching",
      "Care": "Buff with neutral wax cream",
    },
  },
];

export const ABOUT_CONTENT = {
  title: "A Study in Contemporary Silhouette & Fabric Weight",
  paragraphs: [
    "KØRD is an independent clothing shop and fashion label founded on the principles of architectural cut, heavyweight fabric discipline, and timeless versatility. We design wardrobe staples that reject transient fast-fashion cycles.",
    "Every garment in our catalog is engineered with relentless material scrutiny: dense combed organic cotton ranging from 260 to 300 GSM, high-drape tropical wool blends, and full-grain leather footwear crafted for decades of daily wear.",
    "From our relaxed boxy t-shirts to pleated wide-leg trousers and artisan footwear, each release is calibrated for clean proportions, effortless comfort, and enduring modern presence.",
  ],
  stats: [
    { label: "Fabric Longevity", value: "300+ Washes" },
    { label: "Organic Cotton", value: "100% Certified" },
    { label: "Zero Synthetic Blends", value: "Natural Fibers" },
    { label: "Plastic-Free Packaging", value: "Verified" },
  ],
};

export const CONTACT_INFO = {
  conciergeEmail: "orders@kord-apparel.com",
  orderAssistance: "+213 550 12 34 56",
  studioAddress: "14 Rue du Plateau, Algiers, Algeria",
  hours: "Saturday – Thursday: 09:00 – 19:00",
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: "KRD-841920",
    customer: {
      firstName: "Karim",
      lastName: "Mebarki",
      phoneNumber: "+213 550 12 34 56",
      wilaya: "16 - Alger (Algiers)",
      commune: "Hydra",
      deliveryType: "home",
      address: "14 Rue du Plateau, Apt 3B, Hydra, Algiers",
      notes: "Please call before arrival. T-shirt and pants package.",
    },
    items: [
      {
        id: "prod-1-L-Washed Black",
        productId: "prod-1",
        product: PRODUCTS[0],
        quantity: 1,
        selectedSize: "L",
        selectedColor: "Washed Black",
        price: 3600,
      },
      {
        id: "prod-4-XL-Dark Charcoal",
        productId: "prod-4",
        product: PRODUCTS[3],
        quantity: 1,
        selectedSize: "XL",
        selectedColor: "Dark Charcoal",
        price: 5400,
      },
    ],
    subtotal: 9000,
    shippingFee: 800,
    total: 9800,
    createdAt: "2026-09-24T14:32:00Z",
    status: "confirmed",
  },
  {
    id: "KRD-719302",
    customer: {
      firstName: "Yacine",
      lastName: "Belkacem",
      phoneNumber: "+213 661 98 76 54",
      wilaya: "31 - Oran",
      commune: "Oran Centre",
      deliveryType: "home",
      address: "42 Boulevard de la Soummam, Oran",
      notes: "Shoes order, size 42.",
    },
    items: [
      {
        id: "prod-7-42-Off-White & Gray",
        productId: "prod-7",
        product: PRODUCTS[6],
        quantity: 1,
        selectedSize: "42",
        selectedColor: "Off-White & Gray",
        price: 7500,
      },
    ],
    subtotal: 7500,
    shippingFee: 800,
    total: 8300,
    createdAt: "2026-09-23T11:15:00Z",
    status: "processing",
  },
  {
    id: "KRD-604812",
    customer: {
      firstName: "Amine",
      lastName: "Dahmani",
      phoneNumber: "+213 770 45 67 89",
      wilaya: "25 - Constantine",
      commune: "Constantine",
      deliveryType: "office",
      address: "Agency Stop-Desk Constantine Centre",
      notes: "Customer will pick up at stop-desk.",
    },
    items: [
      {
        id: "prod-2-M-Charcoal Black",
        productId: "prod-2",
        product: PRODUCTS[1],
        quantity: 2,
        selectedSize: "M",
        selectedColor: "Charcoal Black",
        price: 4500,
      },
    ],
    subtotal: 9000,
    shippingFee: 500,
    total: 9500,
    createdAt: "2026-09-22T09:40:00Z",
    status: "shipped",
  },
  {
    id: "KRD-529104",
    customer: {
      firstName: "Selim",
      lastName: "Haddad",
      phoneNumber: "+213 560 33 22 11",
      wilaya: "06 - Béjaïa",
      commune: "Béjaïa Ville",
      deliveryType: "home",
      address: "18 Rue de la Liberté, Béjaïa",
      notes: "Derby shoes size 43.",
    },
    items: [
      {
        id: "prod-8-43-Polished Black",
        productId: "prod-8",
        product: PRODUCTS[7],
        quantity: 1,
        selectedSize: "43",
        selectedColor: "Polished Black",
        price: 8800,
      },
    ],
    subtotal: 8800,
    shippingFee: 800,
    total: 9600,
    createdAt: "2026-09-21T16:50:00Z",
    status: "delivered",
  },
  {
    id: "KRD-418290",
    customer: {
      firstName: "Sofiane",
      lastName: "Cherif",
      phoneNumber: "+213 551 88 99 00",
      wilaya: "16 - Alger (Algiers)",
      commune: "Sidi M'Hamed",
      deliveryType: "home",
      address: "22 Rue Didouche Mourad, Alger",
      notes: "T-shirt size 2XL, black.",
    },
    items: [
      {
        id: "prod-3-2XL-Pitch Black",
        productId: "prod-3",
        product: PRODUCTS[2],
        quantity: 1,
        selectedSize: "2XL",
        selectedColor: "Pitch Black",
        price: 3800,
      },
    ],
    subtotal: 3800,
    shippingFee: 800,
    total: 4600,
    createdAt: "2026-09-20T18:20:00Z",
    status: "pending",
  },
];

export const INITIAL_CONTACT_MESSAGES: ContactMessage[] = [
  {
    id: "msg-101",
    name: "Yacine Belkacem",
    email: "yacine.b@archidesign.dz",
    phone: "+213 550 12 34 56",
    subject: "Size advice for Pleated Tailored Trousers",
    inquiryType: "Size & Fit Guidance",
    message: "Bonjour, I usually wear a 32-inch waist in standard trousers. Would you recommend size M or size L for the Pleated Wide-Leg Tailored Trousers? I am 182cm and prefer a slight break over sneakers.",
    createdAt: "2026-09-25T14:32:00Z",
    status: "unread",
    isRead: false,
  },
  {
    id: "msg-102",
    name: "Karim Mebarki",
    email: "karim.mebarki@gmail.com",
    phone: "+213 770 45 67 89",
    subject: "Derby shoes sizing comparison with sneakers",
    inquiryType: "Footwear Sizing",
    orderNumber: "ORD-9428",
    message: "Hello, for the Monolith Lug-Sole Derby Shoes, do they run true to European standard sizes (EU 42) or should I size down compared to the minimalist leather sneakers?",
    createdAt: "2026-09-24T09:15:00Z",
    status: "unread",
    isRead: false,
  },
  {
    id: "msg-103",
    name: "Selim Haddad",
    email: "selim.haddad@outlook.com",
    phone: "+213 560 33 22 11",
    subject: "Heavyweight Boxy Tee fabric care instructions",
    inquiryType: "Fabric & Garment Care",
    message: "I received the 280 GSM Boxy Tee in Washed Black. It feels incredible. To prevent any shrinkage or fading, should I stick to 30°C cold wash and air drying?",
    createdAt: "2026-09-23T18:40:00Z",
    status: "read",
    isRead: true,
  },
  {
    id: "msg-104",
    name: "Nadia Benali",
    email: "nadia.b@studioalger.com",
    phone: "+213 661 22 33 44",
    subject: "Restock query for Chalk White Tee in 2XL and 3XL",
    inquiryType: "Restock & Availability",
    message: "Will the Heavyweight Boxy Crewneck Tee in Chalk White be restocked in sizes 2XL and 3XL soon? Looking to place an order for our creative team.",
    createdAt: "2026-09-21T11:20:00Z",
    status: "replied",
    isRead: true,
    notes: "Restock confirmation sent via email. Size 2XL and 3XL available.",
  },
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  general: {
    storeName: "KØRD Apparel",
    description: "Contemporary minimalist clothing brand. Premium heavyweight t-shirts, tailored pants, and refined footwear crafted with architectural silhouettes.",
    email: "orders@kord-apparel.com",
    phone: "+213 550 12 34 56",
  },
  location: {
    country: "Algeria",
    wilaya: "16 - Alger (Algiers)",
    city: "Hydra",
    address: "14 Rue du Plateau, Boutique KØRD",
    googleMapsUrl: "https://maps.google.com/?q=Hydra+Algiers",
    whatsapp: "+213 550 12 34 56",
  },
  hours: {
    saturdayToThursday: {
      isOpen: true,
      openTime: "09:00",
      closeTime: "19:00",
    },
    friday: {
      isOpen: false,
      openTime: "14:30",
      closeTime: "19:00",
    },
  },
  social: {
    instagram: "https://instagram.com/kord.apparel",
    facebook: "https://facebook.com/kordapparel",
    tiktok: "https://tiktok.com/@kordapparel",
    whatsapp: "+213 550 12 34 56",
  },
  delivery: {
    deliveryEnabled: true,
    officeFee: 500,
    homeFee: 800,
  },
};

export const ALGERIAN_WILAYAS = [
  "01 - Adrar",
  "02 - Chlef",
  "03 - Laghouat",
  "04 - Oum El Bouaghi",
  "05 - Batna",
  "06 - Béjaïa",
  "07 - Biskra",
  "08 - Béchar",
  "09 - Blida",
  "10 - Bouira",
  "11 - Tamanrasset",
  "12 - Tébessa",
  "13 - Tlemcen",
  "14 - Tiaret",
  "15 - Tizi Ouzou",
  "16 - Alger (Algiers)",
  "17 - Djelfa",
  "18 - Jijel",
  "19 - Sétif",
  "20 - Saïda",
  "21 - Skikda",
  "22 - Sidi Bel Abbès",
  "23 - Annaba",
  "24 - Guelma",
  "25 - Constantine",
  "26 - Médéa",
  "27 - Mostaganem",
  "28 - M'Sila",
  "29 - Mascara",
  "30 - Ouargla",
  "31 - Oran",
  "32 - El Bayadh",
  "33 - Illizi",
  "34 - Bordj Bou Arréridj",
  "35 - Boumerdès",
  "36 - El Tarf",
  "37 - Tindouf",
  "38 - Tissemsilt",
  "39 - El Oued",
  "40 - Khenchela",
  "41 - Souk Ahras",
  "42 - Tipaza",
  "43 - Mila",
  "44 - Aïn Defla",
  "45 - Naâma",
  "46 - Aïn Témouchent",
  "47 - Ghardaïa",
  "48 - Relizane",
  "49 - El M'Ghair",
  "50 - El Meniaa",
  "51 - Ouled Djellal",
  "52 - Bordj Baji Mokhtar",
  "53 - Béni Abbès",
  "54 - Timimoun",
  "55 - Touggourt",
  "56 - Djanet",
  "57 - In Salah",
  "58 - In Guezzam",
];
